const SUCCESS_CODE = 200;
const CREATED_CODE = 201;
const ERROR_CODE = 400;
const NOT_FOUND_CODE = 404;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  SUCCESS_CODE,
  CREATED_CODE,
  ERROR_CODE,
  NOT_FOUND_CODE,
  DEFAULT_ERROR_CODE,
};
